# Generated by Django 6.1 on 2026-08-26 01:05

import class_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True, validators=[class_app.validators.validate_subject_format])),
                ('professor', models.CharField(default='Professor Chan', max_length=100, validators=[class_app.validators.validate_professor_name])),
            ],
        ),
    ]
