# Generated by Django 6.1 on 2026-08-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('personal_email', models.CharField(blank=True, max_length=100, null=True)),
                ('locker_number', models.IntegerField()),
                ('locker_combination', models.CharField(max_length=100)),
                ('good_student', models.BooleanField()),
            ],
        ),
    ]
